### ISSUE TITLE
slimv hangs on failure of time.clock()

### ISSUE THREAD

**Issue by freeberz** [kovisoft/slimv#104]
After swank has started, slimv hangs with the following messages:

Getting SWANK connection info...
line   57:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/peter/.vim/ftplugin/swank.py", line 1021, in swank_require
    swank_rex(':swank-require', cmd, 'nil', 't')
  File "/home/peter/.vim/ftplugin/swank.py", line 934, in swank_rex
    swank_send(form)
  File "/home/peter/.vim/ftplugin/swank.py", line 312, in swank_send
    logtime('[---Sent---]')
  File "/home/peter/.vim/ftplugin/swank.py", line 65, in logtime
    logprint(text + ' ' + str(time.clock()))
AttributeError: module 'time' has no attribute 'clock'

Perhaps an issue arising from the deprecation of this function in python 3.3? Replacing the function call with time.process_time() seemed to solve the problem anyway.

I'm running Vim 8.2 on Debian bullseye, and installed slimv from a clone of the Git repo today.

**Comment by kovisoft** [comment]
Please check if you are really using the most recent version of `ftplugin/swank.py`. This problem was fixed in 2018 by commit https://github.com/kovisoft/slimv/commit/e648a3693453e418794bc6d404fd06c92def548f so I guess you have an older version of swank.py lurking around. You can check the scripts loaded into vim by this command:

```
:scriptnames
```
Please look for swank.py and check its version in the displayed location.

**Comment by freeberz** [comment]
You're right, I had version 0.9.13 from 2017 loaded, and I can see the version in my git download has the fix.

Thanks Tamas,

Cheers, Peter
