### ISSUE TITLE
Connect to StumpWM's Lisp image

### ISSUE THREAD

**Issue by MaxGyver83** [kovisoft/slimv#133]
I'm trying to connect to StumpWM's Common Lisp image as described here:
[Hacking StumpWM · stumpwm/stumpwm Wiki](https://github.com/stumpwm/stumpwm/wiki/Hacking-StumpWM)

I start a swank server in my stumpwm config file:

```lisp
(ql:quickload :swank)
(swank:create-server)
```

I can verify that Swank is running by calling:

```shell
$ curl 127.0.0.1:4005
curl: (52) Empty reply from server
```

When I open a lisp file (my StumpWM config) and type `,d` to evaluate a top-level form, I expect that slimv connects to the already running swank server. The wiki page linked at top says, I should then be in the `STUMPWM-USER` package. But I'm not and I can see that slimv starts a new swank server.

Any ideas what I could try?

[swank.log](https://github.com/kovisoft/slimv/files/12516684/swank.log)

**Comment by kovisoft** [comment]
Could you please try first to just connect to the running swank server? So instead of immediately evaluating a form via `,d`, first press `,c` and wait if the swank server is connected. And if the connection is established, then try evaluating the form. Maybe it's some kind of timing issue. From the attached swank.log it seems to me that the evaluation is coming too fast, before all connection messages are processed.

**Comment by MaxGyver83** [comment]
Meanwhile it works both with `,d` directly or first `,c`, then `,d`. I think I had a problem with different SBCL versions and maybe a corrupt cache. Also see this: https://github.com/stumpwm/stumpwm/discussions/1139#discussioncomment-6941961
