### ISSUE TITLE
Remapping <Tab> in Slimv

### ISSUE THREAD

**Issue by siphiuel** [kovisoft/slimv#36]
Hi,

thanks for a great plugin!

I was wondering if there's a way to remap omni-completion from <Tab> to something else? The problem is that i'm used to remapping Tab to Esc in insert mode, and it causes a conflict now.

Thanks,
Vitaliy.

**Comment by kovisoft** [comment]
You can define `g:slimv_unmap_tab` in your `.vimrc` to a nonzero value, this prevents slimv from mapping &lt;Tab&gt;.

You cannot however simply remap `SlimvHandleTab()` on another key, because this function returns `"\<Tab>"` when there's nothing to complete. But maybe you can create your own copy of `function SlimvHandleTab()` by replacing `"<Tab>"` with `""` in the last line, and create your own mapping similar to this one below:

`    inoremap <your-own-key>      <C-R>=YourCopyOfSlimvHandleTab()<CR>`

Or you can just create a function which calls `SlimvHandleTab()` and if the return value is `"\<Tab>"` then it returns `""`, otherwise it just does not change the return value.

If all you want is just the omnicompletion, then you don't need the above fancy mapping, you can just use `<C-X><C-O>`.

Please let me know if something above is not clear, then I'll try to explain the idea more thoroughly.

**Comment by siphiuel** [comment]
Thank you for quick reply!

I followed your advice and added the following to my .vimrc:

```
let slimv_unmap_tab=1

function CustomSlimvHandleTab()
  let result = SlimvHandleTab()
  if result == "\<Tab>"
    return ""
  else
    return result
  endif
endfunction

autocmd FileType lisp inoremap <Leader><Tab> <C-R>=CustomSlimvHandleTab()<CR>
```

Now the autocomplete works for leader followed by Tab (in my case `,<Tab>`).

Thanks again,
Vitaliy.
