### ISSUE TITLE
Trouble with menu

### ISSUE THREAD

**Issue by FiV0** [kovisoft/slimv#53]
I installed slimv and swank runs fine, but when I want to load the menu (`,,`), I get the following errors.
`E333: Menu path must lead to a menu item`
`E334: Menu not found: Slimv.Edit.`

Any idea how to resolve this?
Thanks.

**Comment by kovisoft** [comment]
Please tell me what is the output of these commands:

```
:echo g:slimv_leader
:map ,,
```

This is going to be a long output, first page is enough:

```
:amenu
```

And what happens when you enter this but instead of pressing <Enter> you just press <Tab>?

```
:emenu Slimv.e
```

If `:emenu Slimv.` is printed, then press the <Right> arrow, then `:emenu Slimv.Edit.` should be printed, then just don't delete the trailing `.` character, rather press `<Down>` or `<Enter>`. Then you are in the sub-menu. Does it work?

**Comment by FiV0** [comment]
Sorry I am new to the `:emenu` command. Your last comment helped. 
I did not know you had to press `<Down>`. Everything works perfect now.
