### ISSUE TITLE
How can I control where the SLDB window is shown?

### ISSUE THREAD

**Issue by mihaicristiantanase** [kovisoft/slimv#80]

**Comment by kovisoft** [comment]
I'm not sure I understand the problem. The position of the REPL buffer/window is controlled by the `g:slimv_repl_split` variable (0: new buffer without new window, 1/2/3/4: new window in top/bottom/left/right position). When a form is evaluated in the REPL buffer and a runtime error occurs then the SLDB buffer is opened so that it can be visible and if possible then also the REPL buffer is visible. So in windowed mode the SLDB buffer is opened in a window other than the REPL window (the window next to REPL by vim window number), in non-windowed mode of course the SLDB buffer is brought to the front. There are no additional options for controlling the SLDB window position.

**Comment by mihaicristiantanase** [comment]
Thanks for the quick reply!

**Comment by kovisoft** [comment]
No, there is no separate `g:slimv_XXX_split` option for the XXX buffer. The only option is `g:slimv_repl_split` because the REPL buffer is the very first one that needs to be opened, all other special buffers require that the REPL buffer is open and connected to the swank server.

**Comment by mihaicristiantanase** [comment]
I see. Maybe it's not such a good idea to control the position where the SLDB window shows up.
So, it's a matter of getting use to the automatic behavior. I think :)
